=== c44/Galaxy200/war/Resources/db.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="db">
		<complexType>
			<sequence>
				<element name="users">
					<complexType>
						<sequence>
							<element name="user" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="firstName" type="string" />
										<element name="lastName" type="string" />
										<element name="id" type="string" />
										<element name="birthday">
											<complexType>
												<sequence>
													<element name="day" type="int" />
													<element name="month" type="int" />
													<element name="year" type="int" />
												</sequence>
											</complexType>
										</element>
										<element name="birthday1" type="date" minOccurs="0" />
										<element name="workDays" minOccurs="0" maxOccurs="unbounded">
											<complexType>
												<sequence>
													<element name="workDay" minOccurs="0" maxOccurs="unbounded">
														<complexType>
															<sequence>
																<element name="type">
																	<simpleType>
																		<restriction base="string">
																			<enumeration value="PrivateTraining" />
																			<enumeration value="Targil" />
																		</restriction>
																	</simpleType>
																</element>
																<element name="date" type="date" />
																<element name="approval" type="boolean" />
															</sequence>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
										<element name="branch">
											<simpleType>
												<restriction base="string">
													<enumeration value="North" />
													<enumeration value="South" />
												</restriction>
											</simpleType>
										</element>
										<element name="cell">
											<simpleType>
												<restriction base="string">
													<enumeration value="A" />
													<enumeration value="C" />
													<enumeration value="M" />
												</restriction>
											</simpleType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="cells">
					<complexType>
						<sequence>
							<element name="cell" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="name" type="string" />
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== c44/Galaxy200/war/Resources/dbb.xml
<?xml version="1.0" encoding="UTF-8"?>
<db xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="db.xsd">
	<users>
		<user>
			<firstName>Yonatan</firstName>
			<lastName>Pearlmutter</lastName>
			<id>1</id>
			<birthday>
				<day>15</day>
				<month>11</month>
				<year>1992</year>
			</birthday>
			<workDays>
				<workDay>
					<type>Targil</type>
					<date>2014-04-14</date>
					<approval>true</approval>
				</workDay>
				<workDay>
					<type>Targil</type>
					<date>2014-11-16</date>
					<approval>true</approval>
				</workDay>
				<workDay>
					<type>Targil</type>
					<date>2014-07-25</date>
					<approval>false</approval>
				</workDay>
				<workDay>
					<type>PrivateTraining</type>
					<date>2014-06-17</date>
					<approval>true</approval>
				</workDay>
			</workDays>
			<branch>North</branch>
			<cell>A</cell>
		</user>
		<user>
			<firstName>Neta</firstName>
			<lastName>Stein</lastName>
			<id>2</id>
			<birthday>
				<day>6</day>
				<month>2</month>
				<year>1994</year>
			</birthday>
			<branch>North</branch>
			<cell>A</cell>
		</user>
		<user>
			<firstName>Inbar</firstName>
			<lastName>George</lastName>
			<id>3</id>
			<birthday>
				<day>13</day>
				<month>9</month>
				<year>1993</year>
			</birthday>
			<branch>North</branch>
			<cell>M</cell>
		</user>
		<user>
			<firstName>Or</firstName>
			<lastName>Cohen</lastName>
			<id>4</id>
			<birthday>
				<day>29</day>
				<month>1</month>
				<year>1991</year>
			</birthday>
			<branch>North</branch>
			<cell>M</cell>
		</user>
		<user>
			<firstName>Yoav</firstName>
			<lastName>Alhindi</lastName>
			<id>5</id>
			<birthday>
				<day>21</day>
				<month>4</month>
				<year>1993</year>
			</birthday>
			<branch>South</branch>
			<cell>C</cell>
		</user>
		<user>
			<firstName>Ilana</firstName>
			<lastName>Gunt</lastName>
			<id>6</id>
			<birthday>
				<day>19</day>
				<month>6</month>
				<year>1993</year>
			</birthday>
			<branch>South</branch>
			<cell>M</cell>
		</user>
		<user>
			<firstName>Avigail</firstName>
			<lastName>Rifkin</lastName>
			<id>7</id>
			<birthday>
				<day>12</day>
				<month>7</month>
				<year>1994</year>
			</birthday>
			<branch>South</branch>
			<cell>M</cell>
		</user>
	</users>
	<cells>
		<cell>
			<name>A</name>
		</cell>
		<cell>
			<name>C</name>
		</cell>
		<cell>
			<name>M</name>
		</cell>
	</cells>
</db>
